display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
          tags:
            previous: '‹ Vorherige'
            next: 'Weiter › '
            first: '« Anfang'
            last: 'Ende »'
